### ISSUE TITLE
Sidebar 컴포넌트 (헤더에 버튼 누르면 옆에서 밀려나올 컴포넌트)

### ISSUE THREAD

**Issue by ryu9663** [seulgiryuhun/seulgiryuhun-components#23]
![스크린샷 2024-05-20 오후 3 15 34](https://github.com/seulgiryuhun/seulgiryuhun-components/assets/66232436/ae15a3b4-8f72-4327-b8a5-d302568cb864)

**Comment by olennis** [comment]
0601 논의 내용
- Link 사용시 react-route-dom 의존성 여부 체크

**Comment by ryu9663** [comment]
> 0601 논의 내용
> 
> * Link 사용시 react-route-dom 의존성 여부 체크

리뷰 부탁드려용 https://github.com/seulgiryuhun/seulgiryuhun-components/pull/36

@olennis
