### ISSUE TITLE
props 변경과 Icon 컴포넌트 다시만들기 제안

### ISSUE THREAD

**Issue by ryu9663** [seulgiryuhun/seulgiryuhun-components#29]
@olennis 

개발을 하다 불편한것들이 있어서 제안합니다!

1. default value를 정해놓은 props들이 필수값으로 되어 있어서 default value가 사용될 일이 없음(button의 variant나 color)
   - Icon size의 기본값이 16으로 저장되어있지만 size가 필수값입니다.
   - Button의 의 color, variant도 마찬가지
   - 필수값이 아니어도 괜찮을 것 같음.
```javascript
// Button/index.tsx + type.ts

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  color: ButtonColorType;
  variant: ButtonVariant;
  width?: number;
  height?: number;
  icon?: IconType;
  iconSize?: number;
}

export const Button = ({
  variant = 'filled', // 필수값이라 default value 쓰일일 없음. 그리고 필수여야 하는 이유..?
  color = 'gray',  // 필수값이라 default value 쓰일일 없음. 그리고 필수여야 하는 이유..?
  width = 100,
  height = 40,
  iconSize = 0,
  icon,
  ...props
}: ButtonProps) => {
  const { children } = props;

  return (
    <StyledButton color={color} variant={variant} width={width} height={height} {...props}>
      {icon && <Icon type={icon} size={iconSize} />}
      <span>{children}</span>
    </StyledButton>
  );
};
```

2. Icon type은 유니온 타입이 아닌 string으로 바꾸는게 어떨까요. 왜냐하면 타입제한때문에 외부에서 사용하는 입장에서 자유도가 사라지기 때문
<img width="1174" alt="스크린샷 2024-05-28 오후 10 20 20" src="https://github.com/seulgiryuhun/seulgiryuhun-components/assets/66232436/2236857f-c322-4086-ad72-db0570ae960e">

3. 현재 Icon은 src 밖에 있는 public 폴더만 가져올 수 있는 것으로 보이는데, 이런경우 `src/assets`에서 이미지 관리를 하는 프로젝트에서는 사용할 수 없을 것 같아요. 
```javascript
// Icon/style.ts
export const StyledIcon = styled.i<IconProps>`
  display: inline-flex;
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;

  background-image: url(${({ type }) => `./${type}.svg`}); // 이부분

  width: ${({ size }) => size}px;
  height: ${({ size }) => size}px;
`;

``` 
[쏘카 기술블로그](https://tech.socarcorp.kr/dev/2022/09/06/react-icon-component.html)에서 icon 컴포넌트 만든 방식이 있는데 이거 참고해서 다시 만들어보는 것 어떨까요!

**Comment by olennis** [comment]
@ryu9663 
1. default value를 빼는 쪽으로 진행되면 좋을 것 같습니다! 모든 props들을 optionable 하게 만드는 것은 지양해야 하는 패턴으로 알고 있는데요, 모든 값들을 optionable하게 하는것보다는 default value를 뺀다면 괜찮을 것 같슴다! 

2,3 번도 동감합니다! 리뷰가 긴 호흡으로 진행되다보니 섞여있는것들도 많을것 같은데요, 참고해서 다시 만들어도 좋을 것 같습니다. 
++ 다시 만들면서 IconButton도 같이 작업 되면 좋을 것 같아요!

**Comment by olennis** [comment]
@ryu9663 
위의 코멘트 남겨놓고 문득 든 생각은 string으로 받게 되면 자유도가 너무 생길것 같은데요, 쏘카 블로그를 읽어봐도 이해가 되질 않아서 다시 코멘트 남깁니다! Icon타입이 유니온이 아니라면 (아이콘이 없다면..?) 어떻게 대응이 되나요?

**Comment by olennis** [comment]
0601 논의 내용
- 버튼은 필수값 필요 없음 -> 기본값 설정
- 아이콘은 리액트 풰더- 처럼 사용 (개발자가 아이콘 svg 때려넣고, 유저는 임의의 svg 사용할 수 없음)

**Comment by olennis** [comment]
@ryu9663 
요 이슈 클로즈 처리 해도 될 거 같은데 맞나요?

**Comment by ryu9663** [comment]
@olennis 엤설칫솔마데카솔 도레미파솔! 조한솔! (조한솔은 류준열 초등학교때 친구 이름)
